apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparsom
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 60
    max: 60
    cpuThresholdPercentage: 70
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        tier: db-custom-96-638976
        pointInTimeRecovery: true
        databases:
          - name: sparsom
            envVarPrefix: DATABASE
            users:
            - name: sparsom-api
        flags:
          - name: max_connections
            value: "100"
          - name: max_wal_size
            value: "510848"
          - name: work_mem
            value: "15728640"
          - name: maintenance_work_mem
            value: "268435456"
          - name: effective_cache_size
            value: "57252249"
          - name: random_page_cost
            value: "1.2"
          - name: max_worker_processes
            value: "96"
          - name: max_parallel_workers_per_gather
            value: "4"
          - name: max_parallel_workers
            value: "80"
          - name: max_parallel_maintenance_workers
            value: "64"
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sparsom-v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: KAFKA_MAX_RECORDS
      value: "10"
    - name: KAFKA_MAX_POLL_INTERVAL_MS
      value: "1200000"