apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparsom
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 6Gi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        tier: db-custom-96-638976
        pointInTimeRecovery: false
        databases:
          - name: sparsom
            envVarPrefix: DATABASE
        flags:
          - name: max_wal_size
            value: "510848"
          - name: work_mem
            value: "5242880"
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sparsom-v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: KAFKA_MAX_RECORDS
      value: "10"
    - name: KAFKA_MAX_POLL_INTERVAL_MS
      value: "1200000"
